### ISSUE TITLE
我是下载不了，你们能下载？

### ISSUE THREAD

**Issue by 38602629** [apachecn/huazhang-math-book#1]
我是下载不了，你们能下载？我是下载不了，你们能下载？我是下载不了，你们能下载？

**Comment by jiangzhonglian** [comment]
> 我是下载不了，你们能下载？我是下载不了，你们能下载？我是下载不了，你们能下载？

https://github.com/apachecn/huazhang-math-book/archive/refs/heads/master.zip

试试（需要科学上网）。
